# Generated by Django 5.2.4 on 2025-08-19 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='分类标识')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('icon', models.CharField(default='📚', max_length=50, verbose_name='图标')),
                ('color', models.CharField(default='#667eea', max_length=7, verbose_name='主题色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资源分类',
                'verbose_name_plural': '资源分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='平台名称')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('bilibili', 'Bilibili'), ('github', 'GitHub'), ('stackoverflow', 'Stack Overflow'), ('medium', 'Medium'), ('arxiv', 'arXiv'), ('coursera', 'Coursera'), ('edux', 'edX'), ('custom', '自定义')], max_length=20, verbose_name='平台类型')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='API端点')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('rate_limit', models.IntegerField(default=60, verbose_name='每分钟请求限制')),
                ('priority', models.IntegerField(default=1, verbose_name='优先级')),
            ],
            options={
                'verbose_name': '资源来源',
                'verbose_name_plural': '资源来源',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=200, unique=True, verbose_name='缓存键')),
                ('data', models.JSONField(verbose_name='缓存数据')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资源缓存',
                'verbose_name_plural': '资源缓存',
                'indexes': [models.Index(fields=['expires_at'], name='resource_ag_expires_2843f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('url', models.URLField(verbose_name='资源链接')),
                ('thumbnail', models.URLField(blank=True, verbose_name='缩略图')),
                ('resource_type', models.CharField(choices=[('video', '视频'), ('article', '文章'), ('course', '课程'), ('book', '书籍'), ('documentation', '文档'), ('github', 'GitHub项目'), ('paper', '论文')], max_length=20, verbose_name='资源类型')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='intermediate', max_length=20, verbose_name='难度')),
                ('rating', models.FloatField(default=0.0, verbose_name='评分')),
                ('view_count', models.IntegerField(default=0, verbose_name='观看数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='作者')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='时长')),
                ('language', models.CharField(default='zh-CN', max_length=10, verbose_name='语言')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='外部ID')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_aggregator.resourcecategory', verbose_name='分类')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_aggregator.resourcesource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '学习资源',
                'verbose_name_plural': '学习资源',
                'ordering': ['-rating', '-view_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResourceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '查看'), ('like', '点赞'), ('bookmark', '收藏'), ('share', '分享'), ('complete', '完成')], max_length=20, verbose_name='操作类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('metadata', models.JSONField(default=dict, verbose_name='额外数据')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_aggregator.learningresource', verbose_name='资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资源交互',
                'verbose_name_plural': '用户资源交互',
            },
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['category', 'resource_type'], name='resource_ag_categor_2be048_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['source', 'external_id'], name='resource_ag_source__00512b_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['-rating', '-view_count'], name='resource_ag_rating_53531c_idx'),
        ),
        migrations.AddIndex(
            model_name='userresourceinteraction',
            index=models.Index(fields=['user', 'action'], name='resource_ag_user_id_55be91_idx'),
        ),
        migrations.AddIndex(
            model_name='userresourceinteraction',
            index=models.Index(fields=['resource', 'action'], name='resource_ag_resourc_35d45b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userresourceinteraction',
            unique_together={('user', 'resource', 'action')},
        ),
    ]
