# Generated by Django 5.2.4 on 2025-08-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcecategory',
            options={'ordering': ['order', 'name'], 'verbose_name': '工具分类', 'verbose_name_plural': '工具分类'},
        ),
        migrations.AddField(
            model_name='learningresource',
            name='features',
            field=models.JSONField(default=list, verbose_name='主要功能特性'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='是否免费'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='platform_support',
            field=models.JSONField(default=list, help_text="如: ['Web', 'Windows', 'macOS', 'Linux']", verbose_name='支持平台'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='price_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='价格信息'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='pros_cons',
            field=models.JSONField(default=dict, help_text="格式: {'pros': ['优点1', '优点2'], 'cons': ['缺点1']}", verbose_name='优缺点'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='简短描述'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='usage_tips',
            field=models.TextField(blank=True, verbose_name='使用技巧'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='description',
            field=models.TextField(verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='resource_type',
            field=models.CharField(choices=[('tool', '开发工具'), ('design', '设计工具'), ('ai', 'AI工具'), ('course', '在线课程'), ('video', '视频教程'), ('article', '技术文章'), ('book', '电子书籍'), ('documentation', '官方文档'), ('github', '开源项目'), ('website', '实用网站')], max_length=20, verbose_name='资源类型'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='thumbnail',
            field=models.URLField(blank=True, verbose_name='图标/截图'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='title',
            field=models.CharField(max_length=300, verbose_name='工具/资源名称'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='url',
            field=models.URLField(verbose_name='官方链接'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='icon',
            field=models.CharField(default='🛠️', max_length=50, verbose_name='图标'),
        ),
    ]
