# Generated by Django 5.2.4 on 2025-07-30 11:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='邮箱已验证')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在地')),
                ('website', models.URLField(blank=True, verbose_name='个人网站')),
                ('github_username', models.CharField(blank=True, max_length=100, verbose_name='GitHub用户名')),
                ('total_study_time', models.PositiveIntegerField(default=0, verbose_name='总学习时间(分钟)')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='学习积分')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='用户等级')),
                ('preferred_language', models.CharField(choices=[('zh', '中文'), ('en', 'English')], default='zh', max_length=10, verbose_name='首选语言')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='接收邮件通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='验证令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '邮箱验证令牌',
                'verbose_name_plural': '邮箱验证令牌',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='重置令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '密码重置令牌',
                'verbose_name_plural': '密码重置令牌',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_knowledge_points', models.PositiveIntegerField(default=0, verbose_name='已学知识点数')),
                ('completed_exercises', models.PositiveIntegerField(default=0, verbose_name='完成练习数')),
                ('correct_rate', models.FloatField(default=0.0, verbose_name='正确率')),
                ('study_goal', models.CharField(choices=[('beginner', '入门学习'), ('interview', '面试准备'), ('advanced', '深入研究'), ('review', '复习巩固')], default='beginner', max_length=50, verbose_name='学习目标')),
                ('daily_study_goal', models.PositiveIntegerField(default=30, verbose_name='每日学习目标(分钟)')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='最后学习日期')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='连续学习天数')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='最长连续学习天数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
