# Generated by Django 5.2.4 on 2025-07-30 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True, verbose_name='搜索词')),
                ('search_count', models.PositiveIntegerField(default=0, verbose_name='搜索次数')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='最后搜索时间')),
                ('is_trending', models.BooleanField(default=False, verbose_name='是否热门')),
                ('category', models.CharField(choices=[('data_structure', '数据结构'), ('algorithm', '算法'), ('network', '计算机网络'), ('os', '操作系统'), ('database', '数据库'), ('software_engineering', '软件工程'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
            ],
            options={
                'verbose_name': '热门搜索',
                'verbose_name_plural': '热门搜索',
                'ordering': ['-search_count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='过滤器名称')),
                ('filter_type', models.CharField(choices=[('category', '分类'), ('difficulty', '难度'), ('duration', '时长'), ('status', '状态')], max_length=20, verbose_name='过滤器类型')),
                ('filter_value', models.CharField(max_length=100, verbose_name='过滤值')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '搜索过滤器',
                'verbose_name_plural': '搜索过滤器',
                'ordering': ['filter_type', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgePointIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='标识符')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('content', models.TextField(verbose_name='内容')),
                ('keywords', models.TextField(verbose_name='关键词')),
                ('category', models.CharField(max_length=100, verbose_name='分类')),
                ('subcategory', models.CharField(max_length=100, verbose_name='子分类')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='beginner', max_length=20, verbose_name='难度')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('search_count', models.PositiveIntegerField(default=0, verbose_name='搜索次数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '知识点索引',
                'verbose_name_plural': '知识点索引',
                'indexes': [models.Index(fields=['category', 'subcategory'], name='knowledge_a_categor_bd596c_idx'), models.Index(fields=['difficulty'], name='knowledge_a_difficu_533905_idx'), models.Index(fields=['-view_count'], name='knowledge_a_view_co_061086_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='原始查询')),
                ('suggestion', models.CharField(max_length=200, verbose_name='建议词')),
                ('suggestion_type', models.CharField(choices=[('correction', '拼写纠正'), ('completion', '自动补全'), ('related', '相关搜索'), ('synonym', '同义词')], max_length=20, verbose_name='建议类型')),
                ('confidence', models.FloatField(default=1.0, verbose_name='置信度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '搜索建议',
                'verbose_name_plural': '搜索建议',
                'unique_together': {('query', 'suggestion')},
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='搜索词')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='结果数量')),
                ('clicked_result', models.CharField(blank=True, max_length=100, verbose_name='点击的结果')),
                ('search_time', models.DateTimeField(auto_now_add=True, verbose_name='搜索时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '搜索历史',
                'verbose_name_plural': '搜索历史',
                'ordering': ['-search_time'],
                'indexes': [models.Index(fields=['user', '-search_time'], name='knowledge_a_user_id_3c3692_idx'), models.Index(fields=['query'], name='knowledge_a_query_b11269_idx')],
            },
        ),
    ]
