# Generated by Django 5.2.4 on 2025-07-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0003_exercisecategory_exercisedifficulty_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='专业名词')),
                ('explanation', models.TextField(verbose_name='详细解释')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='所属分类')),
                ('difficulty_level', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='beginner', max_length=20, verbose_name='难度等级')),
                ('extended_info', models.JSONField(blank=True, default=dict, help_text='存储示例、相关链接等额外信息', verbose_name='扩展信息')),
                ('status', models.CharField(choices=[('active', '当前展示'), ('archived', '已归档'), ('draft', '草稿')], default='draft', max_length=20, verbose_name='状态')),
                ('display_date', models.DateField(help_text='该名词展示的日期', unique=True, verbose_name='展示日期')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api_source', models.CharField(default='kimi', max_length=50, verbose_name='API来源')),
                ('api_request_time', models.DateTimeField(blank=True, null=True, verbose_name='API请求时间')),
            ],
            options={
                'verbose_name': '每日名词',
                'verbose_name_plural': '每日名词',
                'ordering': ['-display_date'],
                'indexes': [models.Index(fields=['display_date'], name='knowledge_a_display_844270_idx'), models.Index(fields=['status'], name='knowledge_a_status_cb80bc_idx'), models.Index(fields=['term'], name='knowledge_a_term_a6b7d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TermHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_lower', models.CharField(help_text='用于去重检查的小写名词', max_length=200, unique=True, verbose_name='名词（小写）')),
                ('original_term', models.CharField(max_length=200, verbose_name='原始名词')),
                ('first_used_date', models.DateField(verbose_name='首次使用日期')),
                ('usage_count', models.PositiveIntegerField(default=1, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '名词历史',
                'verbose_name_plural': '名词历史',
                'indexes': [models.Index(fields=['term_lower'], name='knowledge_a_term_lo_ba8438_idx')],
            },
        ),
    ]
