# Generated by Django 5.2.4 on 2025-07-31 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0004_dailyterm_termhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_point', models.CharField(max_length=100, verbose_name='知识点')),
                ('exercises', models.JSONField(help_text='生成的题目数据', verbose_name='练习题目')),
                ('user_answers', models.JSONField(default=list, verbose_name='用户答案')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('total_questions', models.IntegerField(default=0, verbose_name='题目总数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确数量')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('time_spent', models.IntegerField(default=0, verbose_name='用时（秒）')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('difficulty_level', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=20, verbose_name='难度等级')),
                ('api_source', models.CharField(default='kimi', max_length=50, verbose_name='API来源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI练习会话',
                'verbose_name_plural': 'AI练习会话',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'knowledge_point'], name='knowledge_a_user_id_843e7e_idx'), models.Index(fields=['started_at'], name='knowledge_a_started_90987d_idx')],
            },
        ),
    ]
