# Generated by Django 5.2.4 on 2025-08-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0005_aiexercisesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='概念名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('description', models.TextField(verbose_name='概念描述')),
                ('category', models.CharField(choices=[('algorithm', '算法'), ('data_structure', '数据结构'), ('network', '计算机网络'), ('os', '操作系统'), ('database', '数据库'), ('software_engineering', '软件工程'), ('programming', '编程语言'), ('ai', '人工智能'), ('security', '信息安全'), ('architecture', '计算机体系结构'), ('theory', '计算理论'), ('graphics', '计算机图形学'), ('hci', '人机交互'), ('distributed', '分布式系统')], max_length=50, verbose_name='所属分类')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家级')], default='beginner', max_length=20, verbose_name='难度等级')),
                ('importance_weight', models.FloatField(default=1.0, verbose_name='重要性权重')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('learn_count', models.PositiveIntegerField(default=0, verbose_name='学习次数')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='关键词')),
                ('examples', models.JSONField(blank=True, default=list, verbose_name='示例')),
                ('resources', models.JSONField(blank=True, default=list, verbose_name='学习资源')),
                ('graph_position', models.JSONField(blank=True, default=dict, help_text='存储节点在图谱中的坐标信息', verbose_name='图谱位置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '概念节点',
                'verbose_name_plural': '概念节点',
                'ordering': ['category', 'difficulty', 'name'],
                'indexes': [models.Index(fields=['category', 'difficulty'], name='knowledge_a_categor_df54da_idx'), models.Index(fields=['importance_weight'], name='knowledge_a_importa_473301_idx'), models.Index(fields=['is_active'], name='knowledge_a_is_acti_f35736_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='路径名称')),
                ('description', models.TextField(verbose_name='路径描述')),
                ('difficulty_level', models.CharField(choices=[('beginner', '初学者路径'), ('intermediate', '进阶路径'), ('advanced', '高级路径'), ('expert', '专家路径')], default='beginner', max_length=20, verbose_name='难度等级')),
                ('estimated_hours', models.PositiveIntegerField(default=0, verbose_name='预计学习时长(小时)')),
                ('follower_count', models.PositiveIntegerField(default=0, verbose_name='关注人数')),
                ('completion_count', models.PositiveIntegerField(default=0, verbose_name='完成人数')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '学习路径',
                'verbose_name_plural': '学习路径',
                'ordering': ['-is_featured', '-follower_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='顺序')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('estimated_time', models.PositiveIntegerField(default=60, verbose_name='预计学习时间(分钟)')),
                ('notes', models.TextField(blank=True, verbose_name='学习说明')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_app.conceptnode', verbose_name='概念')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_app.learningpath', verbose_name='学习路径')),
            ],
            options={
                'verbose_name': '路径步骤',
                'verbose_name_plural': '路径步骤',
                'ordering': ['learning_path', 'order'],
                'unique_together': {('learning_path', 'concept')},
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='concepts',
            field=models.ManyToManyField(through='knowledge_app.PathStep', to='knowledge_app.conceptnode', verbose_name='包含概念'),
        ),
        migrations.CreateModel(
            name='ConceptRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('prerequisite', '前置关系'), ('related', '相关关系'), ('contains', '包含关系'), ('implements', '实现关系'), ('extends', '扩展关系'), ('uses', '使用关系'), ('similar', '相似关系'), ('opposite', '对立关系')], max_length=20, verbose_name='关系类型')),
                ('strength', models.FloatField(default=0.5, verbose_name='关系强度')),
                ('description', models.TextField(blank=True, verbose_name='关系描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('source_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='knowledge_app.conceptnode', verbose_name='源概念')),
                ('target_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='knowledge_app.conceptnode', verbose_name='目标概念')),
            ],
            options={
                'verbose_name': '概念关系',
                'verbose_name_plural': '概念关系',
                'indexes': [models.Index(fields=['relation_type', 'strength'], name='knowledge_a_relatio_105c63_idx'), models.Index(fields=['is_active'], name='knowledge_a_is_acti_be2436_idx')],
                'unique_together': {('source_concept', 'target_concept', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '学习中'), ('completed', '已完成'), ('mastered', '已掌握')], default='not_started', max_length=20, verbose_name='学习状态')),
                ('mastery_level', models.PositiveIntegerField(default=0, verbose_name='掌握程度')),
                ('total_study_time', models.PositiveIntegerField(default=0, verbose_name='总学习时间(分钟)')),
                ('last_studied_at', models.DateTimeField(blank=True, null=True, verbose_name='最后学习时间')),
                ('study_sessions', models.PositiveIntegerField(default=0, verbose_name='学习次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_app.conceptnode', verbose_name='概念')),
                ('learning_paths', models.ManyToManyField(blank=True, to='knowledge_app.learningpath', verbose_name='相关学习路径')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户学习进度',
                'verbose_name_plural': '用户学习进度',
                'indexes': [models.Index(fields=['user', 'status'], name='knowledge_a_user_id_7be94f_idx'), models.Index(fields=['mastery_level'], name='knowledge_a_mastery_46043c_idx')],
                'unique_together': {('user', 'concept')},
            },
        ),
    ]
