# Generated by Django 5.2.4 on 2025-08-15 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0006_conceptnode_learningpath_pathstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='标签颜色')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
            ],
            options={
                'verbose_name': '题目标签',
                'verbose_name_plural': '题目标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuizLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='题库名称')),
                ('description', models.TextField(blank=True, verbose_name='题库描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='题目总数')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '个人题库',
                'verbose_name_plural': '个人题库',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('fill_blank', '填空题'), ('short_answer', '简答题')], max_length=20, verbose_name='题目类型')),
                ('title', models.CharField(max_length=200, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='选项')),
                ('correct_answer', models.TextField(verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=2, verbose_name='难度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='总答题次数')),
                ('correct_attempts', models.PositiveIntegerField(default=0, verbose_name='正确次数')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge_app.quizlibrary', verbose_name='所属题库')),
                ('tags', models.ManyToManyField(blank=True, to='knowledge_app.quiztag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200, verbose_name='会话名称')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('paused', '已暂停')], default='in_progress', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='总题数')),
                ('answered_questions', models.PositiveIntegerField(default=0, verbose_name='已答题数')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='正确答案数')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_app.quizlibrary', verbose_name='题库')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习会话',
                'verbose_name_plural': '练习会话',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='总练习次数')),
                ('total_questions_answered', models.PositiveIntegerField(default=0, verbose_name='总答题数')),
                ('total_correct_answers', models.PositiveIntegerField(default=0, verbose_name='总正确数')),
                ('total_study_time', models.PositiveIntegerField(default=0, verbose_name='总学习时间(分钟)')),
                ('total_wrong_answers', models.PositiveIntegerField(default=0, verbose_name='总错题数')),
                ('mastered_wrong_answers', models.PositiveIntegerField(default=0, verbose_name='已掌握错题数')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='最后学习日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习统计',
                'verbose_name_plural': '学习统计',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='用户答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='答题用时(秒)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_app.quizquestion', verbose_name='题目')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='knowledge_app.quizsession', verbose_name='练习会话')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'ordering': ['-answered_at'],
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='WrongAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_answer', models.TextField(verbose_name='错误答案')),
                ('correct_answer', models.TextField(verbose_name='正确答案')),
                ('first_wrong_at', models.DateTimeField(auto_now_add=True, verbose_name='首次答错时间')),
                ('last_wrong_at', models.DateTimeField(auto_now=True, verbose_name='最近答错时间')),
                ('wrong_count', models.PositiveIntegerField(default=1, verbose_name='答错次数')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='是否已掌握')),
                ('mastered_at', models.DateTimeField(blank=True, null=True, verbose_name='掌握时间')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='AI分析')),
                ('study_suggestion', models.TextField(blank=True, verbose_name='学习建议')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_app.quizquestion', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '错题记录',
                'verbose_name_plural': '错题记录',
                'ordering': ['-last_wrong_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
