# Generated by Django 5.2.4 on 2025-08-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0007_quiztag_quizlibrary_quizquestion_quizsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='option_images',
            field=models.JSONField(blank=True, default=dict, verbose_name='选项图片'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_questions/', verbose_name='题目图片'),
        ),
    ]
