# Generated by Django 5.2.4 on 2025-08-16 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0008_quizquestion_option_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('public', '公开分享'), ('private', '私密分享'), ('link', '链接分享')], default='private', max_length=10)),
                ('permission', models.CharField(choices=[('view', '仅查看'), ('copy', '可复制'), ('edit', '可编辑')], default='view', max_length=10)),
                ('share_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('message', models.TextField(blank=True, help_text='分享时的留言')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='分享过期时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(blank=True, help_text='最后访问时间', null=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='访问次数')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='knowledge_app.quizlibrary')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_libraries', to=settings.AUTH_USER_MODEL)),
                ('shared_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_libraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_libraries', to=settings.AUTH_USER_MODEL)),
                ('copied_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='knowledge_app.quizlibrary')),
                ('original_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='knowledge_app.quizlibrary')),
                ('share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge_app.libraryshare')),
            ],
        ),
        migrations.AddIndex(
            model_name='libraryshare',
            index=models.Index(fields=['share_code'], name='knowledge_a_share_c_9c9bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryshare',
            index=models.Index(fields=['shared_to', 'is_active'], name='knowledge_a_shared__9b67ba_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryshare',
            index=models.Index(fields=['shared_by', 'created_at'], name='knowledge_a_shared__a8d88b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='libraryshare',
            unique_together={('library', 'shared_by', 'shared_to')},
        ),
    ]
