# Generated by Django 5.2.4 on 2025-08-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0009_libraryshare_librarycopy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='userexerciseattempt',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='exercisesetitem',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exercisesetitem',
            name='exercise_set',
        ),
        migrations.RemoveField(
            model_name='userexercisesetattempt',
            name='exercise_set',
        ),
        migrations.AlterUniqueTogether(
            name='exercisesetitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userexerciseattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userexercisesetattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIExerciseSession',
        ),
        migrations.DeleteModel(
            name='ExerciseDifficulty',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseCategory',
        ),
        migrations.DeleteModel(
            name='ExerciseSetItem',
        ),
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
        migrations.DeleteModel(
            name='UserExerciseAttempt',
        ),
        migrations.DeleteModel(
            name='UserExerciseSetAttempt',
        ),
    ]
